version: '3.8'

services:
  nlp-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: nlpservice:0.0.1
    container_name: nlpservice
    ports:
      - "5000:5000"

networks:
  personal-assistant:
    driver: bridge
