version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: userservice:0.0.1
    container_name: userservice
    ports:
      - "3000:3000"
    networks:
      - personal-assistant
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    ports:
      - "3307:3306"
    networks:
      - personal-assistant
    restart: unless-stopped

networks:
  personal-assistant:
    driver: bridge
